server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fleet_inventory
    username: your_username
    password: your_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO
    com.example.fleet: DEBUG

cors:
  allowed-origins: "*"
  allowed-methods: GET, POST, PUT, DELETE, OPTIONS

ml:
  model-path: classpath:ml/model/usage_predictor.bin

metrics:
  enabled: true
  endpoint: /actuator/metrics

# Additional configurations can be added as needed.